---
#Requires ansible 1.8+
- name: 'YUM Docker - fire and forget task'
  yum: name=docker-io state=installed
  async: 1000
  poll: 0
  register: yum_sleeper
- debug: var=yum_sleeper

- name: 'YUM Docker in progress......'
  async_status: jid={{ yum_sleeper.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 30

- name: 'Download Centos image - fire and forget task'
  command: wget http://centos.mirror.snu.edu.in/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso
  async: 1000
  poll: 0
  register: download_sleeper
- debug: var=download_sleeper

- name: 'Download Centos image in progress......'
  async_status: jid={{ download_sleeper.ansible_job_id }}
  register: result
  until: result.finished
  retries: 100
