---
- include_vars: spoilers.yml
  no_log: true

- name: Put the spoiler text in the tmp directory on the remote server.
  copy:
    content="{{spoiler_text}}"
    dest=/tmp/spoiler_text.txt
  no_log: true
